# Generated by Django 5.1.6 on 2025-03-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("blog_hook", "0001_initial"),
        ("cms", "0036_auto_20240311_1028"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPlugin",
            new_name="BlogPluginModel",
        ),
    ]
